### ISSUE TITLE
Tailseeker problem: name 'TABIX_CMD' is not defined

### ISSUE THREAD

**Issue by fsalmen84** [hyeshik/tailseeker#11]
Hello,

I've just installed tailseeker 3.1.7 on an HPC cluster. And even thou the installation seems fine I can not run the program. This is the error message I get:

(env) [fs@hpcs03 run]$ tseek -j
Tailseeker 3.1.5 - High-throughput measurement of poly(A) tails

NameError in line 101 of /home/bin/tailseeker-3.1.7-bundle-ubuntu_xenial/tailseeker/snakesupport.py:
name 'TABIX_CMD' is not defined
  File "/home/bin/tailseeker-3.1.7-bundle-ubuntu_xenial/tailseeker/main.py", line 32, in <module>
  File "/home/bin/tailseeker-3.1.7-bundle-ubuntu_xenial/tailseeker/snakesupport.py", line 101, in <module>

I have the tailseeker.yaml file in the folder I run the command from and all dependencies are installed and found when I run the setup.sh. Do you have suggestions?

Thanks in advance! Cheers! Fredrik

**Comment by hyeshik** [comment]
Hi Fredrik,

It appears that tailseeker currently does not support the "level 1" installation flawlessly. Sorry for the inconveniences. For now, you may choose level 2 or 3 during the setup or add the following fake line into conf/paths.conf in order to circumvent the NameError.

To the end of conf/paths.conf:

`tabix: /bin/false
`
